name: Publish to WinGet
on:
  release:
    types: [ released ]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        if: github.repository == 'TermoraDev/termora'
        with:
          identifier: TermoraDev.Termora
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
